### ISSUE TITLE
Ảnh minh hoạ trong các post.

### ISSUE THREAD

**Issue by betty2310** [huytd/everyday#1]
Em hay theo dõi blog của anh, anh cho em hỏi các bức illustration, ví dụ như thế này:

![](https://raw.githubusercontent.com/huytd/everyday/master/_meta/cyclic-sort-03.png)

Anh tự vẽ hay là dùng software nào để làm ạ. Em cảm ơn!

**Comment by huytd** [comment]
Hi em, anh dùng phần mềm này https://balsamiq.com

**Comment by betty2310** [comment]
> Hi em, anh dùng phần mềm này https://balsamiq.com

Em cảm ơn anh, em xin phép close issue a!
